# Generated by Django 6.0.2 on 2026-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Sindh', max_length=50),
            preserve_default=False,
        ),
    ]
