# Generated by Django 6.0.2 on 2026-03-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_profile_commit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('core_tech', models.CharField(max_length=100)),
                ('is_free_entry', models.BooleanField()),
                ('difficulty_level', models.IntegerField()),
            ],
        ),
    ]
