# Generated by Django 6.0.3 on 2026-03-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=1000)),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
